name: demo
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup py 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: install requirements py 3.8
        run: pip install -r requirements.txt

      - name: run py test py 3.8
        id: run-py38-test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project tests

      - name: upload test reports py 3.8
        if: failure() && steps.run-py38-test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/

      - name: setup py 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: install requirements py 3.9
        run: pip install -r requirements.txt

      - name: run py test py 3.9
        id: run-py39-test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project tests

      - name: upload test reports py 3.9
        if: failure() && steps.run-py39-test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/

  deploy:
    needs: test-code
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: deploy code
        run: echo "deploy........."
